name: Release Pinny

on:
  push:
    # run only against tags
    tags:
      - "v*.*.*"

permissions: read-all

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
      id-token: write
      # issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bolt
        uses: koalalab-inc/bolt@541cd6f2a1407e5a632621eca92e73475e296c3a # koalalab-inc/bolt@v1 | v1.1.0
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # actions/checkout@v4 | 1567,v4.1.1
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: git fetch --force --tags
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # docker/login-action@v3 | v3.1.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # actions/setup-go@v5 | v5.0.0
        with:
          go-version: 1.21.4
      - name: Install Cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # sigstore/cosign-installer@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # goreleaser/goreleaser-action@v5 | v5.0.0
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
